// <auto-generated />
using InventaMeCF.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace InventaMeCF.Migrations
{
    [DbContext(typeof(InventaMeCFContext))]
    [Migration("20260724164434_AddTablesAAA")]
    partial class AddTablesAAA
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("InventaMeCF.Models.Marca", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Marcas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Nike"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Adidas"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Puma"
                        });
                });

            modelBuilder.Entity("InventaMeCF.Models.Producto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<int>("MarcaId")
                        .HasColumnType("integer");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)")
                        .HasColumnName("Nombre");

                    b.Property<decimal>("PrecioUnitario")
                        .HasPrecision(10, 4)
                        .HasColumnType("numeric(10,4)");

                    b.HasKey("Id");

                    b.HasIndex("MarcaId");

                    b.ToTable("Productos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Descripcion = "Tenis deportivos para uso diario.",
                            MarcaId = 1,
                            Nombre = "Nike Air Max 90",
                            PrecioUnitario = 120.00m
                        },
                        new
                        {
                            Id = 2,
                            Descripcion = "Calzado ligero para correr.",
                            MarcaId = 1,
                            Nombre = "Nike Revolution 7",
                            PrecioUnitario = 85.50m
                        },
                        new
                        {
                            Id = 3,
                            Descripcion = "Tenis deportivos con gran comodidad.",
                            MarcaId = 2,
                            Nombre = "Adidas Ultraboost",
                            PrecioUnitario = 180.00m
                        },
                        new
                        {
                            Id = 4,
                            Descripcion = "Zapatos para fútbol.",
                            MarcaId = 2,
                            Nombre = "Adidas Predator",
                            PrecioUnitario = 95.99m
                        },
                        new
                        {
                            Id = 5,
                            Descripcion = "Tenis casuales unisex.",
                            MarcaId = 3,
                            Nombre = "Puma Smash V2",
                            PrecioUnitario = 70.00m
                        },
                        new
                        {
                            Id = 6,
                            Descripcion = "Calzado deportivo moderno.",
                            MarcaId = 3,
                            Nombre = "Puma Future Rider",
                            PrecioUnitario = 110.75m
                        });
                });

            modelBuilder.Entity("InventaMeCF.Models.Rol", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("Nombre");

                    b.HasKey("Id");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("InventaMeCF.Models.RolAsignado", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("RolId")
                        .HasColumnType("integer");

                    b.Property<int>("RolId1")
                        .HasColumnType("integer");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("RolId");

                    b.HasIndex("RolId1");

                    b.ToTable("RolesAsignados");
                });

            modelBuilder.Entity("InventaMeCF.Models.UnidadMedida", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("UnidadMedidas");
                });

            modelBuilder.Entity("InventaMeCF.Models.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Clave")
                        .IsRequired()
                        .HasColumnType("varchar(64)")
                        .HasColumnName("Clave");

                    b.Property<string>("Correo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("Correo");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)")
                        .HasColumnName("Nombre");

                    b.HasKey("Id");

                    b.ToTable("Usuarios");

                    b.HasData(
                        new
                        {
                            Id = 4,
                            Clave = "8c6976e5b5410415bde908bd4dee15dfb167a9c873fc4bb8a81f6f2ab448a918",
                            Correo = "mcortez_vasquez@yahoo.com",
                            Nombre = "miguel"
                        },
                        new
                        {
                            Id = 5,
                            Clave = "6bab3007f56e2a9175ff1222c2654ddcd08fa7981a1ddc42f1d95cfbd80ede47",
                            Correo = "andrea@gmail.com",
                            Nombre = "andrea"
                        },
                        new
                        {
                            Id = 6,
                            Clave = "a29bb351ab7025926eb34a77f0485a0f8ab9dc993009f990cbd8eabbf0d947e3",
                            Correo = "daniel@gmail.com",
                            Nombre = "daniel"
                        });
                });

            modelBuilder.Entity("InventaMeCF.Models.Producto", b =>
                {
                    b.HasOne("InventaMeCF.Models.Marca", "Marca")
                        .WithMany("Productos")
                        .HasForeignKey("MarcaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Marca");
                });

            modelBuilder.Entity("InventaMeCF.Models.RolAsignado", b =>
                {
                    b.HasOne("InventaMeCF.Models.Usuario", "Usuario")
                        .WithMany("RolesAsignados")
                        .HasForeignKey("RolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("InventaMeCF.Models.Rol", "Rol")
                        .WithMany("RolesAsignados")
                        .HasForeignKey("RolId1")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Rol");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("InventaMeCF.Models.Marca", b =>
                {
                    b.Navigation("Productos");
                });

            modelBuilder.Entity("InventaMeCF.Models.Rol", b =>
                {
                    b.Navigation("RolesAsignados");
                });

            modelBuilder.Entity("InventaMeCF.Models.Usuario", b =>
                {
                    b.Navigation("RolesAsignados");
                });
#pragma warning restore 612, 618
        }
    }
}
