// <auto-generated />
using System;
using InventaMeCF.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace InventaMeCF.Migrations
{
    [DbContext(typeof(InventaMeCFContext))]
    partial class InventaMeCFContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("InventaMeCF.Models.Cliente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .HasColumnType("varchar(80)")
                        .HasColumnName("Nombre");

                    b.HasKey("Id");

                    b.ToTable("Clientes");
                });

            modelBuilder.Entity("InventaMeCF.Models.DetalleVenta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Cantidad")
                        .HasColumnType("integer");

                    b.Property<decimal>("Monto")
                        .HasPrecision(10, 4)
                        .HasColumnType("numeric(10,4)");

                    b.Property<decimal>("PrecioUnitario")
                        .HasPrecision(10, 4)
                        .HasColumnType("numeric(10,4)");

                    b.Property<int>("ProductoId")
                        .HasColumnType("integer");

                    b.Property<int>("VentaId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ProductoId");

                    b.HasIndex("VentaId");

                    b.ToTable("DetalleVentas");
                });

            modelBuilder.Entity("InventaMeCF.Models.Marca", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Marcas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Nike"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Adidas"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Puma"
                        });
                });

            modelBuilder.Entity("InventaMeCF.Models.Producto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<int>("MarcaId")
                        .HasColumnType("integer");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)")
                        .HasColumnName("Nombre");

                    b.Property<decimal>("PrecioUnitario")
                        .HasPrecision(10, 4)
                        .HasColumnType("numeric(10,4)");

                    b.HasKey("Id");

                    b.HasIndex("MarcaId");

                    b.ToTable("Productos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Descripcion = "Tenis deportivos para uso diario.",
                            MarcaId = 1,
                            Nombre = "Nike Air Max 90",
                            PrecioUnitario = 120.00m
                        },
                        new
                        {
                            Id = 2,
                            Descripcion = "Calzado ligero para correr.",
                            MarcaId = 1,
                            Nombre = "Nike Revolution 7",
                            PrecioUnitario = 85.50m
                        },
                        new
                        {
                            Id = 3,
                            Descripcion = "Tenis deportivos con gran comodidad.",
                            MarcaId = 2,
                            Nombre = "Adidas Ultraboost",
                            PrecioUnitario = 180.00m
                        },
                        new
                        {
                            Id = 4,
                            Descripcion = "Zapatos para fútbol.",
                            MarcaId = 2,
                            Nombre = "Adidas Predator",
                            PrecioUnitario = 95.99m
                        },
                        new
                        {
                            Id = 5,
                            Descripcion = "Tenis casuales unisex.",
                            MarcaId = 3,
                            Nombre = "Puma Smash V2",
                            PrecioUnitario = 70.00m
                        },
                        new
                        {
                            Id = 6,
                            Descripcion = "Calzado deportivo moderno.",
                            MarcaId = 3,
                            Nombre = "Puma Future Rider",
                            PrecioUnitario = 110.75m
                        });
                });

            modelBuilder.Entity("InventaMeCF.Models.Rol", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("Nombre");

                    b.HasKey("Id");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nombre = "Administrador"
                        },
                        new
                        {
                            Id = 2,
                            Nombre = "Usuario"
                        });
                });

            modelBuilder.Entity("InventaMeCF.Models.RolAsignado", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("RolId")
                        .HasColumnType("integer");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("RolId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("RolesAsignados");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            RolId = 1,
                            UsuarioId = 1
                        },
                        new
                        {
                            Id = 2,
                            RolId = 2,
                            UsuarioId = 2
                        });
                });

            modelBuilder.Entity("InventaMeCF.Models.UnidadMedida", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("UnidadMedidas");
                });

            modelBuilder.Entity("InventaMeCF.Models.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Clave")
                        .IsRequired()
                        .HasColumnType("varchar(64)")
                        .HasColumnName("Clave");

                    b.Property<string>("Correo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("Correo");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)")
                        .HasColumnName("Nombre");

                    b.HasKey("Id");

                    b.ToTable("Usuarios");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Clave = "ef797c8118f02dfb649607dd5d3f8c7623048c9c063d532cc95c5ed7a898a64f",
                            Correo = "moi@example.com",
                            Nombre = "Moies Aquio"
                        },
                        new
                        {
                            Id = 2,
                            Clave = "1234567890abcdef1234567890abcdef1234567890abcdef1234567890abcdef",
                            Correo = "menr@example.com",
                            Nombre = "Jhonatan Ralu"
                        },
                        new
                        {
                            Id = 3,
                            Clave = "1234567890abcdef1234567890abcdef1234567890abcdef1234567890abcdef",
                            Correo = "bend2@example.com",
                            Nombre = "BEnido juares"
                        });
                });

            modelBuilder.Entity("InventaMeCF.Models.Venta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ClienteId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("Fecha")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("Iva")
                        .HasPrecision(10, 4)
                        .HasColumnType("numeric(10,4)");

                    b.Property<string>("NumeroComprobante")
                        .HasColumnType("varchar(25)")
                        .HasColumnName("NumeroComprobante");

                    b.Property<decimal>("SubTotal")
                        .HasPrecision(10, 4)
                        .HasColumnType("numeric(10,4)");

                    b.Property<decimal>("Total")
                        .HasPrecision(10, 4)
                        .HasColumnType("numeric(10,4)");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Ventas");
                });

            modelBuilder.Entity("InventaMeCF.Models.DetalleVenta", b =>
                {
                    b.HasOne("InventaMeCF.Models.Producto", "Producto")
                        .WithMany("DetalleVentas")
                        .HasForeignKey("ProductoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("InventaMeCF.Models.Venta", "Venta")
                        .WithMany()
                        .HasForeignKey("VentaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Producto");

                    b.Navigation("Venta");
                });

            modelBuilder.Entity("InventaMeCF.Models.Producto", b =>
                {
                    b.HasOne("InventaMeCF.Models.Marca", "Marca")
                        .WithMany("Productos")
                        .HasForeignKey("MarcaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Marca");
                });

            modelBuilder.Entity("InventaMeCF.Models.RolAsignado", b =>
                {
                    b.HasOne("InventaMeCF.Models.Rol", "Rol")
                        .WithMany("RolesAsignados")
                        .HasForeignKey("RolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("InventaMeCF.Models.Usuario", "Usuario")
                        .WithMany("RolesAsignados")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Rol");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("InventaMeCF.Models.Venta", b =>
                {
                    b.HasOne("InventaMeCF.Models.Cliente", "Cliente")
                        .WithMany("Ventas")
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("InventaMeCF.Models.Usuario", "Usuario")
                        .WithMany("Ventas")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cliente");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("InventaMeCF.Models.Cliente", b =>
                {
                    b.Navigation("Ventas");
                });

            modelBuilder.Entity("InventaMeCF.Models.Marca", b =>
                {
                    b.Navigation("Productos");
                });

            modelBuilder.Entity("InventaMeCF.Models.Producto", b =>
                {
                    b.Navigation("DetalleVentas");
                });

            modelBuilder.Entity("InventaMeCF.Models.Rol", b =>
                {
                    b.Navigation("RolesAsignados");
                });

            modelBuilder.Entity("InventaMeCF.Models.Usuario", b =>
                {
                    b.Navigation("RolesAsignados");

                    b.Navigation("Ventas");
                });
#pragma warning restore 612, 618
        }
    }
}
